x-airflow-common:
  &airflow-common
  build: . # <--- ZMIANA: Zamiast image: apache/airflow, budujemy z Dockerfile
  env_file:                 # <--- DODAJEMY TO!
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    PYTHONPATH: "/opt/airflow" 
    # Przekazujemy hosta do Twojego config.py
    DB_HOST: sqlserver
    DB_PASSWORD: "Password1234"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./src:/opt/airflow/src
  depends_on:
    postgres:
      condition: service_healthy

services:
  # ---------------------------------------------------------
  # 1. NASZA HURTOWNIA DANYCH (MS SQL Server)
  # ---------------------------------------------------------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_dwh
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password1234" 
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password1234", "-Q", "SELECT 1", "-C"]
      interval: 10s
      retries: 5
      start_period: 15s
    volumes:
      - mssql_data:/var/opt/mssql

  # ---------------------------------------------------------
  # 2. BAZA WEWNĘTRZNA DLA AIRFLOWA (Postgres)
  # ---------------------------------------------------------
  postgres:
    image: postgres:13
    container_name: airflow_metadata
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  # ---------------------------------------------------------
  # 3. USŁUGI AIRFLOW
  # ---------------------------------------------------------
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  mssql_data: