from loguru import logger
from sqlalchemy import text

from src.db_tools import get_db_engine

CREATE_TABLES_SQL = """
-- 1. Dimension: Date (Generated by our Python script later)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Dim_Date' AND xtype='U')
CREATE TABLE Dim_Date (
    DateKey INT PRIMARY KEY, -- e.g., 20240409 (Smart Key)
    FullDate DATE NOT NULL,
    Year INT NOT NULL,
    Month INT NOT NULL,
    Day INT NOT NULL,
    WeekDayName VARCHAR(20) NOT NULL
);

-- 2. Dimension: Pollutant (Lookup for parameters like PM10, PM2.5)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Dim_Pollutant' AND xtype='U')
CREATE TABLE Dim_Pollutant (
    PollutantKey INT IDENTITY(1,1) PRIMARY KEY,
    ParameterName VARCHAR(50) NOT NULL UNIQUE,
    Unit VARCHAR(20) NOT NULL
);

-- 3. Dimension: Station (SCD Type 2 implementation)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Dim_Station' AND xtype='U')
CREATE TABLE Dim_Station (
    StationKey INT IDENTITY(1,1) PRIMARY KEY, -- Our Surrogate Key
    StationId INT NOT NULL,                   -- Natural Key from OpenAQ API
    StationName VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    -- SCD Type 2 tracking columns
    ValidFrom DATETIME NOT NULL,
    ValidTo DATETIME NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

-- 4. Fact: Air Quality (Central table storing measurements)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Fact_AirQuality' AND xtype='U')
CREATE TABLE Fact_AirQuality (
    FactKey BIGINT IDENTITY(1,1) PRIMARY KEY,
    DateKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Date(DateKey),
    StationKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Station(StationKey),
    PollutantKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Pollutant(PollutantKey),
    MeasurementValue FLOAT NOT NULL,
    MeasurementTime DATETIME NOT NULL,
    
    -- Prevent duplicate measurements for the same station, parameter, and exact time
    CONSTRAINT UQ_Fact_AirQuality UNIQUE (DateKey, StationKey, PollutantKey, MeasurementTime)
);
"""

def initialize_dwh():
    """
    Connects to the SQL Server database and executes the table creation script.
    """
    logger.info("Starting Data Warehouse schema initialization...")
    engine = get_db_engine()
    
    try:
        # engine.begin() automatically handles transactions (commit on success, rollback on error)
        with engine.begin() as conn:
            conn.execute(text(CREATE_TABLES_SQL))
        logger.success("Star Schema tables verified/created successfully.")
    except Exception as e:
        logger.error(f"Failed to initialize schema: {e}")
        raise

if __name__ == "__main__":
    initialize_dwh()